spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/warehousems
    username: postgres
    password: root
    initialization-mode: always
    #platform: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
          lob:
            non_contextual_creation: true