spring:
  application:
    name: gateway-service
server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8099/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    instance-id: ${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2

zuul:
  sensitive-headers: Cookie
  routes:
    product-ms:
      path: /products/**
      serviceId: product-ms
    warehouse-ms:
      path: /warehouses/**
      serviceId: warehouse-ms